# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'lesson20' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for lesson20
pod 'FlexColorPicker'

end
