# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'lesson22_1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for lesson22_1
 pod 'FMDB'


end
